### ISSUE TITLE
CreateSnapshot not compiling

### ISSUE THREAD

**Issue by sayayayayaya** [IanZYYap/android-testing-for-azure-sdk#14]
The [CreateSnapshot](https://github.com/IanZYYap/android-testing-for-azure-sdk/blob/main/azure-samples/src/main/java/com/azuresamples/appconfiguration/CreateSnapshot.java) sample won't compile with GitHub actions or on my local machine, a [whole bunch of classes](https://media.discordapp.net/attachments/1132860171912220732/1150619925610758215/image.png) aren't found on the classpath

**Comment by zjack8** [comment]
Replaced CreateSnapshot with new sample ReadOnly
