### ISSUE TITLE
defaultXmlReader/Writer tests failing

### ISSUE THREAD

**Issue by sayayayayaya** [IanZYYap/android-testing-for-azure-sdk#19]
I know we can't really do anything at the moment, I'm leaving this here so we don't forget about it.

I've commented them out for now in 48551d3, but that's a temporary quick-fix.

**Comment by sayayayayaya** [comment]
Fixed in a2be281

At least for now. When AzureXML is updated the test will start failing again, and we can fix it for good.

**Comment by IanZYYap** [comment]
I've included a TODO comment in the file that states the fix, simply needs to remove the AssertThrows for both tests and update the comments/javadocs to accurately represent the contents of the file to prevent confusion.
